## Data Analyst

- SQL
- Power BI - Charts
- Insights - Charts
- One shot query

## Data Scientist

- Excel
- Pyton - numpy, pandas
- Scale - Millions of rows
- Scikit - Data prediction
- Matplot, seaborn - Charts - (rapid prototyping)
- Line by line (Step)

## Numpy

- Working with arrays (1D)
- Performant (compared Python List)
- C Language
- Staistical oriented - mean, median, mode

In [6]:
import numpy as np

## Numpy way to double an array

In [7]:
marks1 = np.array([90, 80, 20, 40])

print(marks1*2)

[180 160  40  80]


## Python way to double an array

In [ ]:
marks1 = [90, 80, 20, 40]

print([x * 2 for x in marks1])


[180, 160, 40, 80]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[ 1  2  3  4  5  6  7  8  9 10]


## Working with numpy arrays

In [14]:
fives = np.ones(20) * 5

print(fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
counting_to_ten = np.arange(1, 11)

print(counting_to_ten)

[ 1  2  3  4  5  6  7  8  9 10]


In [17]:
odds = np.arange(1, 11, 2)

print(odds)


[1 3 5 7 9]


In [30]:
input = np.arange(0, 201, 2)

print(input)


[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200]


In [31]:
input = np.arange(2,201)

print(input[input % 2 == 0])

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]


In [103]:
ages = np.random.randint(18, 80, 50)

print(ages)

ages_list = ages.tolist()

print(ages_list)

[31 34 52 75 53 30 53 55 47 79 54 27 62 28 68 59 32 37 27 20 43 50 52 26
 76 35 76 64 73 24 28 68 41 31 67 72 56 55 51 20 46 60 53 44 29 48 36 74
 65 24]
[31, 34, 52, 75, 53, 30, 53, 55, 47, 79, 54, 27, 62, 28, 68, 59, 32, 37, 27, 20, 43, 50, 52, 26, 76, 35, 76, 64, 73, 24, 28, 68, 41, 31, 67, 72, 56, 55, 51, 20, 46, 60, 53, 44, 29, 48, 36, 74, 65, 24]


In [106]:
print(ages[ages > 25])


[31 34 52 75 53 30 53 55 47 79 54 27 62 28 68 59 32 37 27 43 50 52 26 76
 35 76 64 73 28 68 41 31 67 72 56 55 51 46 60 53 44 29 48 36 74 65]


## Performance

- Numpy arrays are 100-1000 times the performance of python list
- %%time - time operation

In [ ]:
ages = np.random.randint(18, 60, 500_000)
ages_list = ages.tolist()

In [123]:
%%time
ages_list = [age *2 for age in ages_list]

CPU times: total: 0 ns
Wall time: 10.3 μs


In [118]:
%%time
ages * 2

CPU times: total: 0 ns
Wall time: 1.08 ms


array([ 88,  66, 108, ...,  92,  80,  66], shape=(500000,), dtype=int32)